(() => {
'use strict';
const PRODUCTS = window.PRODUCTS || [];
const $ = (id) => document.getElementById(id);
const els = {form:$('calculatorForm'),search:$('searchProduct'),category:$('category'),product:$('product'),surface:$('surface'),coats:$('coats'),coatsField:$('coatsField'),criterion:$('criterion'),waste:$('waste'),wasteOutput:$('wasteOutput'),preview:$('productPreview'),reset:$('resetButton'),empty:$('resultEmpty'),content:$('resultContent'),amount:$('amountResult'),unit:$('unitResult'),resultProduct:$('resultProduct'),caption:$('resultCaption'),packages:$('packages'),purchase:$('purchaseSummary'),details:$('detailsSection'),technical:$('technical'),formula:$('formula'),toast:$('toast'),install:$('installButton'),connection:$('connectionText'),searchStatus:$('searchStatus')};
let deferredPrompt=null,timer=null;
const fmt=new Intl.NumberFormat('es-AR',{maximumFractionDigits:2});
function toast(msg){clearTimeout(timer);els.toast.textContent=msg;els.toast.hidden=false;timer=setTimeout(()=>els.toast.hidden=true,3000)}
function selected(){return PRODUCTS.find(p=>p.id===els.product.value)}
function categories(){return [...new Set(PRODUCTS.map(p=>p.categoria))].sort((a,b)=>a.localeCompare(b,'es'))}
function renderCategories(){categories().forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=c;els.category.appendChild(o)})}
const SEARCH_SYNONYMS={
'techo':['cubierta','azotea','losa','terraza','cielorraso'],
'pared':['muro','revoque','mamposteria','yeso','ladrillo'],
'humedo':['humedad','filtracion','condensacion'],
'humedad':['humedo','filtracion','condensacion'],
'filtracion':['humedad','gotera','impermeabilizacion'],
'piso':['suelo','cemento','hormigon'],
'metal':['acero','aluminio','hierro','estructura metalica'],
'madera':['puerta','ventana','mueble','deck'],
'bano':['azulejo','ceramica','humedad','vapor'],
'cocina':['azulejo','ceramica','lavable'],
'exterior':['intemperie','frente','fachada'],
'interior':['ambiente','hogar'],
'sellador':['fijador','imprimacion','preparacion'],
'membrana':['impermeabilizante','manta','techo'],
'lavable':['lavado','limpieza'],
'hongo':['antihongo','fungicida','moho']
};
function normalizeText(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function searchText(p){return normalizeText([p.nombre,p.categoria,p.uso,p.preparacion,p.aplicacion,p.acabado,p.recomendaciones,...(p.superficies||[]),...(p.ambientes||[]),...(p.problemas||[]),...(p.tags||[])].join(' '))}
function editDistance(a,b){if(a===b)return 0;if(!a.length)return b.length;if(!b.length)return a.length;let prev=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){const row=[i];for(let j=1;j<=b.length;j++)row[j]=Math.min(row[j-1]+1,prev[j]+1,prev[j-1]+(a[i-1]===b[j-1]?0:1));prev=row}return prev[b.length]}
function tokenMatches(token,words,text){if(text.includes(token))return true;if(token.length<4)return false;const maxDistance=token.length>=8?2:1;return words.some(word=>Math.abs(word.length-token.length)<=maxDistance&&editDistance(token,word)<=maxDistance)}
function matchesSearch(p,query){const normalized=normalizeText(query);if(!normalized)return true;const text=searchText(p);const words=text.split(' ');const tokens=normalized.split(' ').filter(Boolean);return tokens.every(token=>{const alternatives=[token,...(SEARCH_SYNONYMS[token]||[])];return alternatives.some(term=>tokenMatches(normalizeText(term),words,text))})}
function renderProducts(keep=true){const prev=keep?els.product.value:'';const q=els.search.value.trim();const cat=els.category.value;const list=PRODUCTS.filter(p=>(!cat||p.categoria===cat)&&matchesSearch(p,q));els.product.innerHTML='<option value="">Seleccionar producto</option>';list.forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.nombre;els.product.appendChild(o)});if(els.searchStatus){const filters=[];if(q)filters.push(`búsqueda “${q}”`);if(cat)filters.push(cat);els.searchStatus.textContent=list.length===0?'No se encontraron productos. Probá otra palabra o quitá el filtro.':`${list.length} ${list.length===1?'producto encontrado':'productos encontrados'}${filters.length?' para '+filters.join(' · '):''}.`}if(list.some(p=>p.id===prev))els.product.value=prev;else updateProduct()}
function renderCoats(p){els.coats.innerHTML='';const opts=p?.manosOpciones||[1,2,3,4];opts.forEach(n=>{const o=document.createElement('option');o.value=n;o.textContent=`${n} ${n===1?'mano':'manos'}`;if(n===(p?.manosDefault||2))o.selected=true;els.coats.appendChild(o)});const fixed=p?.rendimiento.type==='quantityPerAreaFinished'||p?.calculable===false;els.coatsField.hidden=fixed}
function updateProduct(){const p=selected();if(!p){els.preview.hidden=true;renderCoats(null);hideResults();return}renderCoats(p);const pres=p.calculable===false?'Cálculo automático no disponible':`Presentaciones: ${p.envases.map(x=>p.packageLabels?.[String(x)]||`${fmt.format(x)} ${p.unidad}`).join(' · ')}`;els.preview.innerHTML=`<strong>${p.rendimiento.display}</strong><span>${p.categoria} · ${pres}</span><small>Ficha Rev. ${p.revision||1} · Actualizada ${p.fechaActualizacion||'sin fecha'} · ${p.estadoFicha||'vigente'}</small>`;els.preview.hidden=false;hideResults()}
function yieldValue(p){const r=p.rendimiento;if(els.criterion.value==='min')return r.type==='areaPerUnitPerCoat'?r.min:r.max;if(els.criterion.value==='max')return r.type==='areaPerUnitPerCoat'?r.max:r.min;return (r.min+r.max)/2}
function combination(required,sizes){const sorted=[...sizes].sort((a,b)=>b-a);const smallest=Math.min(...sorted);const maxUnits=Math.ceil(required/smallest)+2;let best=null;function rec(i,total,counts){if(total>=required){const excess=total-required;const units=counts.reduce((a,b)=>a+b,0);const score=excess*1000+units;if(!best||score<best.score)best={score,total,counts:[...counts]};return}if(i>=sorted.length)return;const size=sorted[i];const max=Math.min(maxUnits,Math.ceil((required-total)/size)+2);for(let n=max;n>=0;n--){counts[i]=n;rec(i+1,total+n*size,counts);counts[i]=0}}rec(0,0,new Array(sorted.length).fill(0));return {items:sorted.map((size,i)=>({size,count:best?.counts[i]||0})).filter(x=>x.count),total:best?.total||0}}
function calculate(){const p=selected();const area=Number(els.surface.value);if(!p){toast('Seleccioná un producto.');els.product.focus();return}if(p.calculable===false){showInformational(p);return}if(!Number.isFinite(area)||area<=0){toast('Ingresá una superficie mayor a cero.');els.surface.focus();return}const waste=Number(els.waste.value);const criterion=yieldValue(p);let base,total,coats=Number(els.coats.value)||1,formula;if(p.rendimiento.type==='areaPerUnitPerCoat'){base=area*coats/criterion;total=base*(1+waste/100);formula=`(${fmt.format(area)} m² × ${coats} manos ÷ ${fmt.format(criterion)} m²/${p.unidad.slice(0,-1)}) × 1,${String(waste).padStart(2,'0')}`}else if(p.rendimiento.type==='quantityPerAreaPerCoat'){base=area*coats*criterion;total=base*(1+waste/100);formula=`(${fmt.format(area)} m² × ${coats} manos × ${fmt.format(criterion)} ${p.unidad}/m²) × 1,${String(waste).padStart(2,'0')}`}else{base=area*criterion;total=base*(1+waste/100);formula=`(${fmt.format(area)} m² × ${fmt.format(criterion)} ${p.unidad}/m²) × 1,${String(waste).padStart(2,'0')}`}total=Math.ceil(total*100)/100;const combo=combination(total,p.envases);showResults(p,area,coats,waste,criterion,total,combo,formula)}
function showResults(p,area,coats,waste,criterion,total,combo,formula){els.empty.hidden=true;els.content.hidden=false;els.details.hidden=false;els.resultProduct.textContent=p.nombre;els.amount.textContent=fmt.format(total);els.unit.textContent=p.unidad;els.caption.textContent=p.rendimiento.type==='areaPerUnitPerCoat'?`${fmt.format(area)} m² · ${coats} manos · ${waste}% de desperdicio · rendimiento usado ${fmt.format(criterion)} m² por ${p.unidad.slice(0,-1)} y mano`:`${fmt.format(area)} m² · trabajo terminado · ${waste}% de desperdicio · consumo usado ${fmt.format(criterion)} ${p.unidad}/m²`;els.packages.innerHTML=combo.items.map(x=>`<div class="package-chip"><strong>${x.count}×</strong> ${p.packageLabels?.[String(x.size)]||`${fmt.format(x.size)} ${p.unidad}`}</div>`).join('');els.purchase.textContent=`Compra total sugerida: ${fmt.format(combo.total)} ${p.unidad}. Sobrante estimado: ${fmt.format(Math.max(0,combo.total-total))} ${p.unidad}.`;const rows=[['Rendimiento',p.rendimiento.display],['Manos recomendadas',p.manosRecomendadas],['Presentaciones',p.envases.map(x=>fmt.format(x)).join(', ')+' '+p.unidad],['Uso',p.uso],['Preparación',p.preparacion],['Aplicación',p.aplicacion],['Acabado',p.acabado],['Secado al tacto',p.tiempos.tacto],['Entre manos',p.tiempos.entreManos],['Secado final',p.tiempos.final],['Revisión de ficha',`Rev. ${p.revision||1} · Versión ${p.versionFicha||'1.0'}`],['Última actualización',p.fechaActualizacion||'Sin fecha'],['Estado de ficha',p.estadoFicha||'vigente'],['Fuente',p.fuenteFicha||'Ficha técnica FADEPA'],['Recomendaciones',p.recomendaciones]];els.technical.innerHTML=rows.map(([a,b])=>`<dt>${a}</dt><dd>${b}</dd>`).join('');els.formula.innerHTML=`<strong>${formula}</strong><span>Resultado: ${fmt.format(total)} ${p.unidad}</span>`;els.details.scrollIntoView({behavior:'smooth',block:'nearest'})}
function showInformational(p){els.empty.hidden=true;els.content.hidden=false;els.details.hidden=false;els.resultProduct.textContent=p.nombre;els.amount.textContent='—';els.unit.textContent='consulta técnica';els.caption.textContent=p.recomendaciones;els.packages.innerHTML=Object.values(p.packageLabels||{}).map(x=>`<div class="package-chip">${x}</div>`).join('');els.purchase.textContent='Este producto figura en la base, pero la aplicación no convierte automáticamente volumen a peso sin una equivalencia oficial.';const rows=[['Rendimiento informado',p.rendimiento.display],['Manos recomendadas',p.manosRecomendadas],['Uso',p.uso],['Preparación',p.preparacion],['Aplicación',p.aplicacion],['Acabado',p.acabado],['Secado al tacto',p.tiempos.tacto],['Entre manos',p.tiempos.entreManos],['Secado final',p.tiempos.final],['Revisión de ficha',`Rev. ${p.revision||1} · Versión ${p.versionFicha||'1.0'}`],['Última actualización',p.fechaActualizacion||'Sin fecha'],['Estado de ficha',p.estadoFicha||'vigente'],['Fuente',p.fuenteFicha||'Ficha técnica FADEPA'],['Advertencia',p.recomendaciones]];els.technical.innerHTML=rows.map(([a,b])=>`<dt>${a}</dt><dd>${b}</dd>`).join('');els.formula.innerHTML='<strong>Cálculo bloqueado por seguridad técnica</strong><span>La ficha usa unidades comerciales y de rendimiento que no permiten una conversión directa sin densidad oficial.</span>';els.details.scrollIntoView({behavior:'smooth',block:'nearest'})}
function hideResults(){els.content.hidden=true;els.empty.hidden=false;els.details.hidden=true}
function reset(){els.form.reset();els.search.value='';els.category.value='';els.wasteOutput.textContent='10%';renderProducts(false);renderCoats(null);hideResults()}
els.search.addEventListener('input',()=>renderProducts(false));els.category.addEventListener('change',()=>renderProducts(false));els.product.addEventListener('change',updateProduct);els.waste.addEventListener('input',()=>els.wasteOutput.textContent=`${els.waste.value}%`);els.form.addEventListener('submit',e=>{e.preventDefault();calculate()});els.reset.addEventListener('click',reset);
function connection(){els.connection.textContent=navigator.onLine?'Disponible sin conexión':'Trabajando sin conexión'}window.addEventListener('online',connection);window.addEventListener('offline',connection);
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;els.install.hidden=false});els.install.addEventListener('click',async()=>{if(!deferredPrompt){toast('Usá el menú del navegador y elegí “Agregar a pantalla principal”.');return}deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;els.install.hidden=true});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(console.error));
renderCategories();renderProducts(false);renderCoats(null);connection();
})();