/* Calculadora FADEPA · Segmento 01 · v0.3.4
   Agrega 6 productos calculables sin reemplazar ni duplicar la base existente.
   Cargar este archivo después de products.js y antes de app.js.
*/
(() => {
  'use strict';

  const products = [
    {
      id: 'acrilicos-de-colores',
      nombre: 'Acrílicos de Colores Interior / Exterior',
      categoria: 'Látex y paredes',
      unidad: 'litros',
      rendimiento: { min: 9, max: 14, type: 'areaPerUnitPerCoat', display: '9 a 14 m² por litro y por mano' },
      envases: [1, 4, 10, 20],
      manosDefault: 2,
      manosOpciones: [1, 2, 3],
      manosRecomendadas: 'La ficha no fija una cantidad única de manos. Para la estimación inicial se sugieren 2 manos; ajustar según color, fondo y poder cubritivo.',
      recomendaciones: 'Aplicar con consistencia normal o con la mínima cantidad de agua necesaria. Sobre mampostería nueva usar Sellador Fijador Concentrado diluido 1:2. Sobre metal aplicar antes dos manos de Fondo Convertidor y Antióxido Gris.',
      tiempos: { entreManos: '4 horas', final: '7 días', tacto: '1,5 horas' },
      preparacion: 'Superficie limpia, seca, desengrasada y libre de óxido, polvo y hongos.',
      aplicacion: 'Pincel, rodillo o soplete.',
      acabado: 'Mate',
      uso: 'Mampostería y metal, en interiores y exteriores.',
      superficies: ['mampostería', 'revoque', 'ladrillo', 'fibrocemento', 'metal', 'pared'],
      ambientes: ['interior', 'exterior'],
      problemas: ['decoración', 'protección', 'intemperie'],
      tags: ['acrílico', 'colores', 'látex', 'pared', 'fachada'],
      revision: 1, versionFicha: '1.0', fechaActualizacion: '2026-07-24',
      estadoFicha: 'vigente', fuenteFicha: 'Ficha técnica FADEPA', searchVersion: 1
    },
    {
      id: 'barniz-al-agua-brillante',
      nombre: 'Barniz al Agua Brillante',
      categoria: 'Maderas y barnices',
      unidad: 'litros',
      rendimiento: { min: 8, max: 10, type: 'areaPerUnitPerCoat', display: '8 a 10 m² por litro y por mano' },
      envases: [0.5, 1, 4, 20],
      manosDefault: 3,
      manosOpciones: [1, 2, 3, 4],
      manosRecomendadas: 'Sobre madera nueva: 1 mano inicial diluida 15% con agua y luego las manos restantes sin diluir. Sobre barniz al agua en buen estado: 2 o 3 manos.',
      recomendaciones: 'Para exterior incorporar como mínimo 30 cm³ de Entonador para Madera FADEPA por cada litro de barniz.',
      tiempos: { entreManos: '8 horas', final: '24 horas', tacto: '2 horas' },
      preparacion: 'Madera limpia, seca, desengrasada y libre de polvo o barniz viejo mal adherido.',
      aplicacion: 'Pincel, rodillo o soplete.',
      acabado: 'Brillante transparente',
      uso: 'Maderas interiores y exteriores: pisos, zócalos, puertas, ventanas y muebles.',
      superficies: ['madera', 'piso de madera', 'zócalo', 'puerta', 'ventana', 'mueble'],
      ambientes: ['interior', 'exterior'],
      problemas: ['protección', 'desgaste', 'intemperie'],
      tags: ['barniz', 'agua', 'brillante', 'madera', 'uretánico'],
      revision: 1, versionFicha: '1.0', fechaActualizacion: '2026-07-24',
      estadoFicha: 'vigente', fuenteFicha: 'Ficha técnica FADEPA', searchVersion: 1
    },
    {
      id: 'barniz-al-agua-mate',
      nombre: 'Barniz al Agua Mate',
      categoria: 'Maderas y barnices',
      unidad: 'litros',
      rendimiento: { min: 8, max: 10, type: 'areaPerUnitPerCoat', display: '8 a 10 m² por litro y por mano' },
      envases: [0.5, 1, 4, 20],
      manosDefault: 3,
      manosOpciones: [1, 2, 3, 4],
      manosRecomendadas: 'Sobre madera nueva: 1 mano inicial diluida 10% con agua y luego las manos siguientes sin diluir. Sobre barniz al agua en buen estado: 2 o 3 manos.',
      recomendaciones: 'Para exterior incorporar como mínimo 30 cm³ de Entonador para Madera FADEPA por cada litro. Como bicapa de Piso Deportivo interior, diluir 1 L de barniz en 1 L de agua.',
      tiempos: { entreManos: '8 horas', final: '24 horas', tacto: '2 horas' },
      preparacion: 'Madera limpia, seca, desengrasada y libre de polvo o barniz viejo mal adherido.',
      aplicacion: 'Pincel, rodillo o soplete.',
      acabado: 'Mate transparente',
      uso: 'Maderas interiores y exteriores; uso secundario como bicapa interior para pisos deportivos.',
      superficies: ['madera', 'piso de madera', 'zócalo', 'puerta', 'ventana', 'mueble'],
      ambientes: ['interior', 'exterior'],
      problemas: ['protección', 'desgaste', 'terminación mate'],
      tags: ['barniz', 'agua', 'mate', 'madera', 'bicapa'],
      revision: 1, versionFicha: '1.0', fechaActualizacion: '2026-07-24',
      estadoFicha: 'vigente', fuenteFicha: 'Ficha técnica FADEPA', searchVersion: 1
    },
    {
      id: 'bloqueador-antihumedad',
      nombre: 'Bloqueador Antihumedad',
      categoria: 'Humedad e impermeabilización',
      unidad: 'litros',
      rendimiento: { min: 3, max: 5, type: 'areaPerUnitPerCoat', display: '3 a 5 m² por litro y por mano' },
      envases: [1, 4],
      manosDefault: 3,
      manosOpciones: [3],
      manosRecomendadas: 'La ficha exige 3 manos para asegurar un bloqueo correcto.',
      recomendaciones: 'Si fuera necesario, diluir con la mínima cantidad de thinner o Diluyente para Demarcación Vial. Bloquea la humedad en la zona tratada, pero no elimina la causa de origen.',
      tiempos: { entreManos: '4 horas', final: '24 horas', tacto: '2 horas' },
      preparacion: 'Rasquetear hasta eliminar todo lo flojo o pulverulento y llegar a una base firme.',
      aplicacion: 'Pincel, rodillo o soplete.',
      acabado: 'Blanco, lavable y de secado rápido',
      uso: 'Paredes interiores y exteriores con humedad retenida, manchas, hongos o salitre.',
      superficies: ['pared', 'mampostería', 'revoque'],
      ambientes: ['interior', 'exterior'],
      problemas: ['humedad', 'salitre', 'hongos', 'manchas'],
      tags: ['antihumedad', 'bloqueador', 'solvente', 'pared', 'salitre'],
      revision: 1, versionFicha: '1.0', fechaActualizacion: '2026-07-24',
      estadoFicha: 'vigente', fuenteFicha: 'Ficha técnica FADEPA', searchVersion: 1
    },
    {
      id: 'enduido-plastico-interior-exterior',
      nombre: 'Enduido Plástico Interior / Exterior',
      categoria: 'Preparación de superficies',
      unidad: 'litros',
      rendimiento: { min: 1, max: 1, type: 'areaPerUnitPerCoat', display: '1 m² por litro con espesor uniforme de 1 mm' },
      envases: [0.5, 1, 4, 10, 20],
      manosDefault: 1,
      manosOpciones: [1, 2, 3],
      manosRecomendadas: 'El número de manos depende de las exigencias del trabajo. El rendimiento informado corresponde a una capa uniforme de 1 mm.',
      recomendaciones: 'Aplicar en capas delgadas. La cantidad real varía según profundidad de imperfecciones y espesor aplicado.',
      tiempos: { entreManos: '3 a 4 horas', final: '8 horas', tacto: 'No especificado en la ficha' },
      preparacion: 'Eliminar polvo y partes flojas. Aplicar previamente una mano de Sellador Fijador diluido 1:2.',
      aplicacion: 'Espátula, goma o llana metálica.',
      acabado: 'Superficie lisa y lijable',
      uso: 'Revoque, yeso y otras superficies interiores o exteriores.',
      superficies: ['revoque', 'yeso', 'pared'],
      ambientes: ['interior', 'exterior'],
      problemas: ['imperfecciones', 'desnivel', 'alisado'],
      tags: ['enduido', 'plástico', 'pared', 'reparación', 'llana'],
      revision: 1, versionFicha: '1.0', fechaActualizacion: '2026-07-24',
      estadoFicha: 'vigente', fuenteFicha: 'Ficha técnica FADEPA', searchVersion: 1
    },
    {
      id: 'cubierta-pisos-deportivos-chapas',
      nombre: 'Cubierta para Pisos Deportivos y Chapas Galvanizadas',
      categoria: 'Pisos y cubiertas',
      unidad: 'litros',
      rendimiento: { min: 8, max: 10, type: 'areaPerUnitPerCoat', display: '8 a 10 m² por litro y por mano' },
      envases: [1, 4, 10, 20],
      manosDefault: 3,
      manosOpciones: [1, 2, 3],
      manosRecomendadas: 'Piso de hormigón nuevo: 1 mano diluida 20% a 30% y 2 manos sin diluir. Chapa galvanizada nueva: 1 mano sin diluir y 2 manos con mínima dilución. Superficie pintada: 2 manos.',
      recomendaciones: 'Para superficies nuevas usar 3 manos. En pisos interiores puede agregarse 1 o 2 manos de Barniz al Agua Mate diluido 50%, que no están incluidas en este cálculo.',
      tiempos: { entreManos: '5 horas', final: '7 días de sol', tacto: '2 horas' },
      preparacion: 'Superficie limpia, seca, desengrasada, libre de óxido y polvo.',
      aplicacion: 'Pincel o rodillo.',
      acabado: 'No altera las propiedades térmicas ni antideslizantes del piso original',
      uso: 'Pisos deportivos, bordes de piletas, solarios y chapas galvanizadas.',
      superficies: ['piso de hormigón', 'chapa galvanizada', 'piso deportivo', 'solario'],
      ambientes: ['interior', 'exterior'],
      problemas: ['desgaste', 'protección', 'intemperie'],
      tags: ['piso', 'deportivo', 'chapa', 'galvanizada', 'pileta', 'solario'],
      revision: 1, versionFicha: '1.0', fechaActualizacion: '2026-07-24',
      estadoFicha: 'vigente', fuenteFicha: 'Ficha técnica FADEPA', searchVersion: 1
    }
  ];

  const current = Array.isArray(window.PRODUCTS) ? window.PRODUCTS : [];
  const existingIds = new Set(current.map(product => product.id));
  window.PRODUCTS = current.concat(products.filter(product => !existingIds.has(product.id)));
})();
