/* Calculadora FADEPA · Segmento 09 · v0.4.2
   Agrega 10 productos verificados contra fichas técnicas oficiales.
   Los productos sin rendimiento por superficie quedan informativos.
*/
(() => {
  'use strict';

  const products = [
    {
      id:'aditivo-doble-accion',
      nombre:'Aditivo Doble Acción (Convertidor y Antióxido)',
      categoria:'Aditivos',
      calculable:false,
      unidad:'envase',
      rendimiento:{type:'informational',display:'Dosificación: 250 cm³ cada 4 litros de Esmalte Sintético'},
      envases:[0.25],
      packageLabels:{'0.25':'Envase de 250 cm³'},
      manosDefault:1,manosOpciones:[1],
      manosRecomendadas:'Se incorpora al esmalte antes de aplicarlo.',
      recomendaciones:'Convierte un Esmalte Sintético brillante, satinado o mate en un esmalte triple acción. No posee rendimiento propio por m².',
      tiempos:{entreManos:'Depende del esmalte utilizado',final:'Depende del esmalte utilizado',tacto:'No corresponde'},
      preparacion:'Agregar el contenido completo de 250 cm³ a 4 litros de esmalte y mezclar hasta homogeneizar.',
      aplicacion:'Aditivo para mezcla.',
      acabado:'Depende del esmalte utilizado',
      uso:'Aditivación anticorrosiva de esmaltes sintéticos.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'aditivo-poliuretanico-base-acuosa',
      nombre:'Aditivo Poliuretánico Base Acuosa',
      categoria:'Aditivos',
      calculable:false,
      unidad:'kg',
      rendimiento:{type:'informational',display:'Dosificación general: 1 kg cada 10 litros de pintura'},
      envases:[1],
      packageLabels:{'1':'Envase de 1 kg'},
      manosDefault:1,manosOpciones:[1],
      manosRecomendadas:'Se incorpora a la pintura antes de aplicarla.',
      recomendaciones:'Para convertir Látex Acrílico Color Estándar en membrana poliuretánica, la ficha indica 2 kg cada 10 litros. Para otros usos generales, 1 kg cada 10 litros.',
      tiempos:{entreManos:'Depende de la pintura utilizada',final:'Depende de la pintura utilizada',tacto:'No corresponde'},
      preparacion:'Adicionar mediante mezcla enérgica hasta homogeneizar.',
      aplicacion:'Aditivo bicomponente base acuosa.',
      acabado:'Depende de la pintura utilizada',
      uso:'Mejora lavabilidad, adherencia, impermeabilidad, elasticidad y resistencia.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'antihongo-antialga-concentrado',
      nombre:'Antihongo - Antialga Concentrado',
      categoria:'Aditivos',
      calculable:false,
      unidad:'envase',
      rendimiento:{type:'informational',display:'Dosificación: 60 cm³ cada 4 litros de pintura al látex'},
      envases:[0.06],
      packageLabels:{'0.06':'Envase de 60 cm³'},
      manosDefault:1,manosOpciones:[1],
      manosRecomendadas:'Se incorpora al látex antes de pintar.',
      recomendaciones:'Producto biocida. Utilizar guantes y protección ocular. No dejar al alcance de niños y evitar contaminación de cursos de agua.',
      tiempos:{entreManos:'No modifica el secado del látex',final:'Depende del látex utilizado',tacto:'No corresponde'},
      preparacion:'Si existen hongos, limpiar primero con lavandina diluida 1:3, enjuagar y dejar secar.',
      aplicacion:'Disolver un envase de 60 cm³ en 4 litros de pintura al látex y mezclar bien.',
      acabado:'Depende del látex utilizado',
      uso:'Protección contra hongos, algas y levaduras en interiores y exteriores.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'base-niveladora',
      nombre:'Base Niveladora',
      categoria:'Preparación de superficies',
      calculable:false,
      unidad:'kg',
      rendimiento:{type:'informational',display:'La ficha no informa rendimiento por m² ni presentaciones comerciales'},
      envases:[],
      manosDefault:1,manosOpciones:[1],
      manosRecomendadas:'Aplicar según el espesor y el defecto que se deba nivelar.',
      recomendaciones:'Lista para usar en espesores menores a 5 mm. Para 5 a 10 mm: agregar 1 kg de cemento Portland y 1 kg de arena fina cada 30 kg de Base Niveladora.',
      tiempos:{entreManos:'No especificado',final:'No especificado',tacto:'No especificado'},
      preparacion:'Superficie firme, sin polvo, partes flojas, grasitud ni hongos. Se recomienda Sellador Fijador diluido 1:3.',
      aplicacion:'Espátula o llana metálica.',
      acabado:'Base nivelada para revestir',
      uso:'Nivelación interior y exterior de superficies irregulares.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'cemento-blanco',
      nombre:'Cemento Blanco',
      categoria:'Preparación de superficies',
      calculable:false,
      unidad:'kg',
      rendimiento:{type:'informational',display:'La ficha no informa rendimiento por m²'},
      envases:[1.25],
      packageLabels:{'1.25':'Bolsa de 1,250 kg'},
      manosDefault:1,manosOpciones:[1],
      manosRecomendadas:'Aplicar según el trabajo de reparación.',
      recomendaciones:'Preparar únicamente la cantidad necesaria mezclando con agua hasta formar una pasta.',
      tiempos:{entreManos:'No corresponde',final:'48 horas',tacto:'No especificado'},
      preparacion:'Aplicar sobre mampostería u hormigón sin pintar.',
      aplicacion:'Espátula o herramienta apropiada para reparación.',
      acabado:'Cementicio blanco',
      uso:'Rellenos, parches, revestimientos cementicios y usos industriales.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'entonador-rojo-ceramico',
      nombre:'Entonador Rojo Cerámico',
      categoria:'Entonadores',
      calculable:false,
      unidad:'sachet',
      rendimiento:{type:'informational',display:'Dosificación: 1 sachet de 30 cm³ cada 4 litros de Impermeabilizante Acrílico Incoloro'},
      envases:[0.03],
      packageLabels:{'0.03':'Sachet de 30 cm³'},
      manosDefault:1,manosOpciones:[1],
      manosRecomendadas:'Preparar suficiente producto entonado para completar una mano.',
      recomendaciones:'Compatible exclusivamente con Impermeabilizante Acrílico Incoloro. Aporta color, no poder cubritivo.',
      tiempos:{entreManos:'Depende del impermeabilizante',final:'Depende del impermeabilizante',tacto:'No corresponde'},
      preparacion:'Incorporar primero en una porción del impermeabilizante y luego mezclar con el resto.',
      aplicacion:'Entonador para mezcla.',
      acabado:'Rojo cerámico',
      uso:'Coloración del Impermeabilizante Acrílico Incoloro.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'entonador-universal-para-barnices',
      nombre:'Entonador Universal para Barnices',
      categoria:'Entonadores',
      calculable:false,
      unidad:'sachet',
      rendimiento:{type:'informational',display:'30 cm³ por litro de barniz, laca o impregnante; o 30 cm³ en 500 cm³ de aguarrás para teñir madera'},
      envases:[0.03],
      packageLabels:{'0.03':'Sachet de 30 cm³'},
      manosDefault:1,manosOpciones:[1],
      manosRecomendadas:'Mezclar hasta lograr uniformidad de color.',
      recomendaciones:'Compatible con barnices, lacas e impregnantes acuosos o al solvente indicados en la ficha.',
      tiempos:{entreManos:'Depende del recubrimiento',final:'Depende del recubrimiento',tacto:'No corresponde'},
      preparacion:'Para teñir madera, mezclar 30 cm³ en 500 cm³ de aguarrás y esperar 24 horas antes del recubrimiento protector.',
      aplicacion:'Directo sobre madera o incorporado al recubrimiento.',
      acabado:'Cedro, caoba, nogal, roble claro, roble oscuro, algarrobo o wengue',
      uso:'Coloración de maderas, barnices, lacas e impregnantes.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'diluyente-poliuretano-fadepa-2k',
      nombre:'Diluyente para Poliuretano FADEPA 2K',
      categoria:'Diluyentes',
      calculable:false,
      unidad:'envase',
      rendimiento:{type:'informational',display:'Dosificación: 10% a 20% sobre la mezcla de Poliuretano 2K'},
      envases:[0.25],
      packageLabels:{'0.25':'Envase de 250 cm³'},
      manosDefault:1,manosOpciones:[1],
      manosRecomendadas:'Agregar después de mezclar completamente los componentes A y B.',
      recomendaciones:'Utilizar únicamente con Esmalte Poliuretánico 2K FADEPA. Producto inflamable; trabajar con ventilación y protección adecuada.',
      tiempos:{entreManos:'No corresponde',final:'No corresponde',tacto:'No corresponde'},
      preparacion:'Homogeneizar A, incorporar B durante dos minutos y luego agregar entre 10% y 20% de diluyente.',
      aplicacion:'Diluyente para mezcla.',
      acabado:'Incoloro',
      uso:'Ajuste de aplicación y extensión del pot-life del Poliuretano 2K.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'esmalte-poliuretanico-2k',
      nombre:'Esmalte Poliuretánico 2K',
      categoria:'Esmaltes especiales',
      calculable:false,
      unidad:'kit',
      rendimiento:{min:10,max:10,type:'informational',display:'10 m² por litro y por mano; kits comerciales formulados por peso y según color'},
      envases:[],
      manosDefault:2,manosOpciones:[1,2,3],
      manosRecomendadas:'Aplicar las manos necesarias, dejando 6 horas entre manos.',
      recomendaciones:'Cálculo automático bloqueado: el rendimiento está expresado en litros, pero los componentes se presentan por peso y varían según color, sin densidad oficial única.',
      tiempos:{entreManos:'6 horas',final:'No especificado en el extracto de ficha',tacto:'Pot-life aproximado: 1 hora 30 minutos'},
      preparacion:'Superficie limpia, seca y libre de polvo y grasa. Utilizar la base correspondiente porque no es autoimprimante.',
      aplicacion:'Pincel, rodillo o soplete; diluir 10% a 20% con Diluyente Poliuretánico FADEPA 2K.',
      acabado:'Brillante o satinado, transparente o de color',
      uso:'Terminación de metal y madera correctamente preparados.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'mezcla-adhesiva-plastica',
      nombre:'Mezcla Adhesiva Plástica Interior / Exterior',
      categoria:'Preparación de superficies',
      calculable:false,
      unidad:'kg',
      rendimiento:{type:'informational',display:'La ficha no informa rendimiento por m²'},
      envases:[1.25,5],
      packageLabels:{'1.25':'Bolsa de 1,250 kg','5':'Bolsa de 5 kg'},
      manosDefault:1,manosOpciones:[1],
      manosRecomendadas:'Aplicar según el espesor requerido.',
      recomendaciones:'Mezclar aproximadamente 2,5 partes de producto con 1 parte de agua. Preparar pequeñas cantidades: trabajabilidad aproximada de 15 minutos.',
      tiempos:{entreManos:'No especificado',final:'45 horas; máxima resistencia',tacto:'Inicial: 15 a 30 minutos; lijado: 12 horas'},
      preparacion:'Superficie limpia, sin polvo ni partes mal adheridas. No aplicar en lugares con humedad.',
      aplicacion:'Espátula, realizando leve presión.',
      acabado:'Reparable, recubrible y lijable',
      uso:'Reparación, recubrimiento y relleno de mampostería, hormigón y yeso.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    }
  ];

  const current=Array.isArray(window.PRODUCTS)?window.PRODUCTS:[];
  const ids=new Set(current.map(p=>p.id));
  window.PRODUCTS=current.concat(products.filter(p=>!ids.has(p.id)));
})();
