/* Calculadora FADEPA · Segmento final 12 · v0.4.5
   Incorpora las fichas técnicas oficiales que permanecían sin registrar.
*/
(() => {
  'use strict';

  const products = [
    {
      id:'latex-dekorativ',
      nombre:'Látex Dekorativ',
      categoria:'Látex y paredes',
      unidad:'litros',
      rendimiento:{min:8,max:14,type:'areaPerUnitPerCoat',display:'8 a 14 m² por litro y por mano'},
      envases:[1,4,10,20],
      manosDefault:2,manosOpciones:[1,2,3],
      manosRecomendadas:'Habitualmente 2 manos, según cobertura y estado de la superficie.',
      recomendaciones:'Dejar como mínimo 3 horas entre manos. En mampostería nueva aplicar Sellador - Fijador Concentrado diluido 1:2.',
      tiempos:{entreManos:'3 horas',final:'7 días',tacto:'1,5 horas'},
      preparacion:'Superficie limpia, seca, desengrasada y libre de polvo, óxido y hongos.',
      aplicacion:'Pincel, rodillo o soplete, con consistencia normal o mínima cantidad de agua.',
      acabado:'Mate aterciopelado',
      uso:'Paredes interiores y cielorrasos; admite bases tintométricas P y T.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',
      estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'yeso',
      nombre:'Yeso',
      categoria:'Preparación de superficies',
      calculable:false,
      unidad:'kg',
      rendimiento:{type:'informational',display:'La ficha no informa rendimiento por m²'},
      envases:[1],
      packageLabels:{'1':'Bolsa de 1 kg'},
      manosDefault:1,manosOpciones:[1],
      manosRecomendadas:'Aplicar según la profundidad y extensión de la reparación.',
      recomendaciones:'Preparar únicamente la cantidad que pueda utilizarse dentro de aproximadamente 5 minutos.',
      tiempos:{entreManos:'No corresponde',final:'48 horas',tacto:'Lijado: 12 horas'},
      preparacion:'Pared interior sin pintar.',
      aplicacion:'Mezclar con agua hasta formar una pasta líquida y aplicar sobre la reparación.',
      acabado:'Relleno lijable y pintable',
      uso:'Relleno y reparación de paredes interiores.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',
      estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'triple-accion-esmalte-antioxido-convertidor',
      nombre:'Triple Acción - Esmalte, Antióxido y Convertidor',
      categoria:'Esmaltes',
      unidad:'litros',
      rendimiento:{min:12,max:18,type:'areaPerUnitPerCoat',display:'12 a 18 m² por litro y por mano'},
      envases:[0.25,0.5,1,4,20],
      manosDefault:2,manosOpciones:[2,3,4],
      manosRecomendadas:'Aplicar como mínimo 2 manos; ajustar según protección, color y estado del metal.',
      recomendaciones:'Primera mano: máximo 15% de aguarrás. Manos siguientes: máximo 10%. Para Grafito se recomienda una mano previa de Convertidor Gris.',
      tiempos:{entreManos:'12 horas',final:'24 horas',tacto:'4 a 6 horas'},
      preparacion:'Superficie limpia, seca, desengrasada y libre de polvo y pintura floja. En metal se recomienda Limpia Metal.',
      aplicacion:'Pincel, rodillo o soplete.',
      acabado:'Brillante o satinado',
      uso:'Protección y terminación de hierro y metal; también puede emplearse sobre madera y mampostería correctamente preparadas.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',
      estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'zeroox-convertidor-oxido-base-acuosa',
      nombre:'Zeroox - Convertidor de Óxido Base Acuosa',
      categoria:'Fondos y antióxidos',
      unidad:'litros',
      rendimiento:{min:20,max:20,type:'areaPerUnitPerCoat',display:'20 m² por litro y por mano'},
      envases:[0.12],
      packageLabels:{'0.12':'Sachet de 120 ml'},
      manosDefault:2,manosOpciones:[2],
      manosRecomendadas:'La ficha indica 2 manos.',
      recomendaciones:'Listo para usar; no diluir. No devolver al envase producto que haya estado en contacto con el metal.',
      tiempos:{entreManos:'4 horas',final:'No especificado en la ficha',tacto:'No especificado en la ficha'},
      preparacion:'Aplicar directamente sobre metal nuevo u oxidado, limpio y libre de contaminantes.',
      aplicacion:'Pincel, rodillo o soplete.',
      acabado:'Mate transparente',
      uso:'Conversión y estabilización del óxido antes de pinturas base agua o solvente.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',
      estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'revestimiento-acrilico-estucado',
      nombre:'Revestimiento Acrílico Estucado',
      categoria:'Revestimientos decorativos',
      unidad:'kg',
      rendimiento:{min:1,max:1,type:'quantityPerAreaFinished',display:'Aproximadamente 1 kg por m² de trabajo'},
      envases:[1,10,20],
      manosDefault:2,manosOpciones:[2],
      manosRecomendadas:'Dos capas de colores, seguidas del lijado y la protección con Barniz Mate al Agua.',
      recomendaciones:'La ficha expresa el rendimiento en kg, aunque las presentaciones están declaradas en litros. El cálculo estima consumo en kg, sin convertirlo a volumen.',
      tiempos:{entreManos:'4 horas',final:'Depende del sistema completo',tacto:'No especificado en la ficha'},
      preparacion:'Superficie interior limpia, seca, libre de polvo, grasa, material flojo, hongos y humedad.',
      aplicacion:'Llana plástica en capas finas; lijado posterior para efecto símil mármol.',
      acabado:'Liso, pulido y brillante, símil mármol',
      uso:'Decoración de paredes interiores mediante técnica de espatulado.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',
      estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'limpiador-restos-de-obras',
      nombre:'Limpiador Restos de Obras',
      categoria:'Limpieza y preparación',
      calculable:false,
      unidad:'litros',
      rendimiento:{type:'informational',display:'Dosificación variable según uso: puro, 1:1, 1:4, 1:10 o 1 L cada 20.000 L de agua'},
      envases:[1,5],
      manosDefault:1,manosOpciones:[1],
      manosRecomendadas:'Una aplicación, dejando actuar aproximadamente 30 minutos y luego hidrolavando.',
      recomendaciones:'Ácido muriático al 20%. Colocar primero el agua y luego el producto. No mezclar con álcalis ni otras sustancias. Usar protección completa.',
      tiempos:{entreManos:'No corresponde',final:'Actuación aproximada: 30 minutos',tacto:'No corresponde'},
      preparacion:'Realizar una prueba en una zona pequeña y no aplicar sobre superficies calientes.',
      aplicacion:'Aplicar según la dilución correspondiente y luego hidrolavar.',
      acabado:'Limpiador ácido',
      uso:'Restos de obra, salitre, alcalinidad, cerámicos, pastinas y regulación de pH de piscinas.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',
      estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'revestimiento-texturado-extra-fino',
      nombre:'Revestimiento Acrílico Texturado Impermeable - Extra Fino',
      categoria:'Revestimientos texturados',
      unidad:'kg',
      rendimiento:{min:1.6,max:2.0,type:'quantityPerAreaFinished',display:'1,8 ± 0,2 kg/m² de trabajo terminado'},
      envases:[1.5,15,30],
      manosDefault:1,manosOpciones:[1,2,3],
      manosRecomendadas:'A rodillo se recomiendan como mínimo 3 manos; a soplete puede ser suficiente 1 mano.',
      recomendaciones:'El rendimiento corresponde al trabajo terminado y depende del espesor y de la nivelación requerida. Contemplar 10% adicional.',
      tiempos:{entreManos:'3 a 5 horas a rodillo',final:'5 a 7 días',tacto:'3 a 8 horas'},
      preparacion:'Superficie firme, seca, limpia y libre de grasa. En superficies nuevas aplicar una impresión de látex del mismo color.',
      aplicacion:'Rodillo de pelo corto o especial para texturar, o soplete de salpicar.',
      acabado:'Mate, texturado e impermeable',
      uso:'Paredes interiores y exteriores.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',
      estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'revestimiento-texturado-fino',
      nombre:'Revestimiento Acrílico Texturado Impermeable - Fino',
      categoria:'Revestimientos texturados',
      unidad:'kg',
      rendimiento:{min:2.3,max:2.7,type:'quantityPerAreaFinished',display:'2,5 ± 0,2 kg/m² de trabajo terminado'},
      envases:[1.5,15,30],
      manosDefault:1,manosOpciones:[1,2,3],
      manosRecomendadas:'Con llana se aplica según terminación; a rodillo se recomiendan como mínimo 3 manos.',
      recomendaciones:'El rendimiento corresponde al trabajo terminado y depende del espesor y de la nivelación requerida. Contemplar 10% adicional.',
      tiempos:{entreManos:'3 a 5 horas a rodillo',final:'5 a 7 días',tacto:'3 a 8 horas'},
      preparacion:'Superficie firme, seca, limpia y libre de grasa. En superficies nuevas aplicar una impresión de látex del mismo color.',
      aplicacion:'Llana, rodillo de pelo corto o especial para texturar, o soplete de salpicar.',
      acabado:'Mate, texturado e impermeable; permite rulado o travertino',
      uso:'Paredes interiores y exteriores.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',
      estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'revestimiento-texturado-medio',
      nombre:'Revestimiento Acrílico Texturado Impermeable - Medio',
      categoria:'Revestimientos texturados',
      unidad:'kg',
      rendimiento:{min:3.3,max:3.7,type:'quantityPerAreaFinished',display:'3,5 ± 0,2 kg/m² de trabajo terminado'},
      envases:[1.5,15,30],
      manosDefault:1,manosOpciones:[1],
      manosRecomendadas:'Aplicación con llana metálica y terminación con llana plástica lisa.',
      recomendaciones:'El rendimiento corresponde al trabajo terminado y depende del espesor y de la nivelación requerida. Contemplar 10% adicional.',
      tiempos:{entreManos:'No corresponde normalmente',final:'5 a 7 días',tacto:'3 a 8 horas'},
      preparacion:'Superficie firme, seca, limpia y libre de grasa. En superficies nuevas aplicar una impresión de látex del mismo color.',
      aplicacion:'Llana metálica para aplicar y llana plástica lisa para terminar.',
      acabado:'Mate, texturado e impermeable; permite rulado o travertino',
      uso:'Paredes interiores y exteriores.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',
      estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    }
  ];

  const current=Array.isArray(window.PRODUCTS)?window.PRODUCTS:[];
  const ids=new Set(current.map(p=>p.id));
  window.PRODUCTS=current.concat(products.filter(p=>!ids.has(p.id)));
})();
