/* Calculadora FADEPA · Segmento 10 · v0.4.3
   Agrega 10 productos verificados contra fichas técnicas oficiales FADEPA.
*/
(() => {
  'use strict';

  const products = [
    {
      id:'fondo-antioxido-industrial',
      nombre:'Fondo Antióxido Industrial',
      categoria:'Fondos y antióxidos',
      unidad:'litros',
      rendimiento:{min:12,max:14,type:'areaPerUnitPerCoat',display:'12 a 14 m² por litro y por mano'},
      envases:[0.25,0.5,1,4,20],
      manosDefault:2,manosOpciones:[2],
      manosRecomendadas:'La ficha indica dos manos; la primera diluida con aguarrás.',
      recomendaciones:'Dejar 12 horas antes de aplicar la segunda mano o la pintura de acabado.',
      tiempos:{entreManos:'12 horas',final:'No especificado en la ficha',tacto:'4 horas'},
      preparacion:'Superficie limpia, seca, desengrasada, libre de polvo y pintura vieja mal adherida.',
      aplicacion:'Pincel o rodillo.',
      acabado:'Mate',
      uso:'Protección anticorrosiva de superficies ferrosas.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'impermeabilizante-acrilico-ladrillos-tejas',
      nombre:'Impermeabilizante Acrílico para Ladrillos y Tejas',
      categoria:'Impermeabilización',
      unidad:'litros',
      rendimiento:{min:8,max:15,type:'areaPerUnitPerCoat',display:'8 a 15 m² por litro y por mano'},
      envases:[1,4,10,20],
      manosDefault:4,manosOpciones:[4],
      manosRecomendadas:'Para una buena impermeabilización: 1 mano diluida 30% y 3 manos sin diluir.',
      recomendaciones:'Puede colorearse con Entonador Rojo Cerámico, 1 sachet de 30 cm³ cada 4 litros.',
      tiempos:{entreManos:'3 horas',final:'7 días',tacto:'No especificado en la ficha'},
      preparacion:'Superficie limpia, seca y desengrasada. Eliminar hongos y eflorescencia salina antes de aplicar.',
      aplicacion:'Pincel, rodillo o soplete.',
      acabado:'Brillante transparente',
      uso:'Ladrillo visto y tejas, en interior y exterior.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'doble-impacto-recubrimiento-elastomerico',
      nombre:'Doble Impacto - Recubrimiento Elastomérico',
      categoria:'Látex y paredes',
      unidad:'litros',
      rendimiento:{min:8,max:15,type:'areaPerUnitPerCoat',display:'8 a 15 m² por litro y por mano'},
      envases:[1,4,10,20],
      manosDefault:2,manosOpciones:[1,2,3],
      manosRecomendadas:'La ficha no fija una cantidad única; se sugieren 2 manos como estimación inicial.',
      recomendaciones:'Diluir con la mínima cantidad de agua posible, entre 5% y 10%.',
      tiempos:{entreManos:'4 horas',final:'7 días',tacto:'1 hora'},
      preparacion:'Superficie limpia, seca, desengrasada y libre de polvo, pintura floja y hongos.',
      aplicacion:'Pincel, rodillo o soplete airless.',
      acabado:'Mate aterciopelado',
      uso:'Interiores y exteriores; máxima lavabilidad en interior.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'entonadores-pintura-base-acuosa',
      nombre:'Entonadores para Pintura Base Acuosa',
      categoria:'Entonadores',
      calculable:false,
      unidad:'envase',
      rendimiento:{type:'informational',display:'Dosificación máxima variable según la pintura; consultar ficha resumida'},
      envases:[0.03,0.12],
      packageLabels:{'0.03':'Envase de 30 cm³','0.12':'Envase de 120 cm³'},
      manosDefault:1,manosOpciones:[1],
      manosRecomendadas:'Se incorporan a la pintura antes de aplicar.',
      recomendaciones:'Dosificaciones máximas: Profesional Interior 15 cm³/L; Concentrado 30 cm³/L; Profesional Exterior 15 cm³/L; Satinado 45 cm³/L; Cielorraso 7,5 cm³/L; Plus Ecológico 5 cm³/L; Nacional 5 cm³/L; Doble Impacto 35 cm³/L.',
      tiempos:{entreManos:'Depende de la pintura utilizada',final:'Depende de la pintura utilizada',tacto:'No corresponde'},
      preparacion:'Mezclar primero con una porción de pintura y luego incorporar al resto hasta homogeneizar.',
      aplicacion:'Entonador para mezcla.',
      acabado:'Color según entonador elegido',
      uso:'Coloración de pinturas al látex e impermeabilizantes compatibles.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'latizador-fijador-pintura-cal',
      nombre:'Latizador - Fijador para Pintura a la Cal',
      categoria:'Aditivos',
      calculable:false,
      unidad:'envase',
      rendimiento:{type:'informational',display:'Dosificación de ficha: 120 cm³ para 4 kg de cal y 10 litros de agua'},
      envases:[0.12],
      packageLabels:{'0.12':'Envase de 120 cm³'},
      manosDefault:1,manosOpciones:[1],
      manosRecomendadas:'Agregar al preparar la pintura a la cal.',
      recomendaciones:'Mejora adherencia, resistencia al frote y al ataque microbiano; reduce descuelgue y entizado.',
      tiempos:{entreManos:'Depende de la pintura a la cal',final:'Depende de la pintura a la cal',tacto:'No corresponde'},
      preparacion:'Preparar 4 kg de cal con 10 litros de agua, agregar el contenido del envase y homogeneizar.',
      aplicacion:'Aditivo para mezcla.',
      acabado:'Depende de la pintura a la cal',
      uso:'Fijación y mejora de pinturas a la cal.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'membrana-cristal',
      nombre:'Membrana Cristal',
      categoria:'Impermeabilización',
      calculable:false,
      unidad:'litros',
      rendimiento:{type:'informational',display:'La ficha no informa rendimiento por m²'},
      envases:[0.5,1],
      manosDefault:2,manosOpciones:[2,3],
      manosRecomendadas:'Aplicar como mínimo 2 manos.',
      recomendaciones:'Producto listo para usar. No diluir. No puede lijarse ni pintarse con otros productos.',
      tiempos:{entreManos:'No especificado en la ficha',final:'12 horas',tacto:'No especificado en la ficha'},
      preparacion:'Superficie seca, limpia y libre de polvo, aceite y suciedad.',
      aplicacion:'Pincel o rodillo.',
      acabado:'Mate; blanco, negro o transparente',
      uso:'Impermeabilización de techos y grietas sobre cemento, hormigón, tejas, madera y metal.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'profesional-exterior-interior',
      nombre:'Profesional Exterior - Interior (Lavable - Antihongo)',
      categoria:'Látex y paredes',
      unidad:'litros',
      rendimiento:{min:8,max:14,type:'areaPerUnitPerCoat',display:'8 a 14 m² por litro y por mano'},
      envases:[1,4,10,20],
      manosDefault:2,manosOpciones:[1,2,3],
      manosRecomendadas:'Habitualmente 2 manos; ajustar según cobertura y estado de la superficie.',
      recomendaciones:'Dejar al menos 3 horas entre manos. Sobre superficies pulverulentas usar Sellador Fijador Concentrado diluido 1:2,5.',
      tiempos:{entreManos:'3 horas',final:'7 días',tacto:'1,5 horas'},
      preparacion:'Superficie limpia, seca, desengrasada y libre de óxido, polvo y hongos.',
      aplicacion:'Pincel, rodillo o soplete.',
      acabado:'Mate',
      uso:'Paredes interiores y exteriores.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'recubrimiento-piscina-plastico-fibra-cemento',
      nombre:'Recubrimiento para Piscina - Plástico, Fibra y Cemento',
      categoria:'Piletas',
      unidad:'litros',
      rendimiento:{min:8,max:12,type:'areaPerUnitPerCoat',display:'8 a 12 m² por litro y por mano'},
      envases:[1,4,20],
      manosDefault:2,manosOpciones:[2,3],
      manosRecomendadas:'La ficha recomienda entre 2 y 3 manos.',
      recomendaciones:'Primera mano diluida 20% para mejorar el anclaje y segunda con mínima dilución. No llenar hasta pasados 7 días de sol.',
      tiempos:{entreManos:'12 horas',final:'7 días de sol antes del llenado',tacto:'2 a 4 horas'},
      preparacion:'Superficie limpia, seca, libre de algas, grasa y polvo. Lijar con lija al agua grano 120 y limpiar.',
      aplicacion:'Pincel, rodillo o soplete.',
      acabado:'Azul o celeste',
      uso:'Piscinas plásticas, de fibra de vidrio y de cemento.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'manta-elastica-impermeable-fibrada',
      nombre:'Manta Elástica Impermeable Fibrada para Techos',
      categoria:'Techos e impermeabilización',
      unidad:'kg',
      rendimiento:{min:1,max:1.25,type:'quantityPerAreaFinished',display:'1 a 1,25 kg/m² de trabajo terminado, con 4 manos'},
      envases:[1.2,4.8,12,24],
      manosDefault:4,manosOpciones:[4],
      manosRecomendadas:'4 manos: primera diluida 30% y tres manos sin diluir.',
      recomendaciones:'El consumo informado corresponde al trabajo terminado. No multiplicar nuevamente por la cantidad de manos.',
      tiempos:{entreManos:'4 horas',final:'24 horas',tacto:'No especificado en la ficha'},
      preparacion:'Superficie limpia, seca, desengrasada y libre de óxido y polvo. Redondear aristas y ángulos.',
      aplicacion:'Pincel, rodillo o soplete.',
      acabado:'Mate',
      uso:'Impermeabilización de techos, losas, revoques y ladrillos.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'imprimacion-fijadora-al-agua',
      nombre:'Imprimación Fijadora al Agua',
      categoria:'Fondos y selladores',
      unidad:'litros',
      rendimiento:{min:10,max:10,type:'areaPerUnitPerCoat',display:'10 m² por litro y por mano'},
      envases:[1,4,10,20],
      manosDefault:1,manosOpciones:[1],
      manosRecomendadas:'La ficha indica una mano.',
      recomendaciones:'Puede diluirse hasta 10% con agua si fuera necesario.',
      tiempos:{entreManos:'No corresponde',final:'12 horas',tacto:'4 horas'},
      preparacion:'Superficie limpia, seca y desengrasada; eliminar partes flojas, polvo y capas gruesas de pintura a la cal.',
      aplicacion:'Pincel, rodillo o soplete.',
      acabado:'Mate blanco',
      uso:'Fijar, sellar y uniformar absorción antes de pinturas al látex.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    }
  ];

  const current=Array.isArray(window.PRODUCTS)?window.PRODUCTS:[];
  const ids=new Set(current.map(p=>p.id));
  window.PRODUCTS=current.concat(products.filter(p=>!ids.has(p.id)));
})();
