/* Calculadora FADEPA · Segmento 11 · v0.4.4
   Agrega 10 productos verificados contra fichas técnicas oficiales FADEPA.
   No se inventan rendimientos ni conversiones ausentes o inconsistentes.
*/
(() => {
  'use strict';

  const products = [
    {
      id:'fondo-gris-colores-bajo-cubritivo',
      nombre:'Fondo Gris para Colores de Bajo Cubritivo',
      categoria:'Fondos y selladores',
      unidad:'litros',
      rendimiento:{min:8,max:14,type:'areaPerUnitPerCoat',display:'8 a 14 m² por litro y por mano'},
      envases:[1,4,10,20],
      manosDefault:1,manosOpciones:[1],
      manosRecomendadas:'Se utiliza como una mano de unificación y base para el color posterior.',
      recomendaciones:'Sobre mampostería nueva aplicar previamente Sellador - Fijador Concentrado diluido 1:2.',
      tiempos:{entreManos:'3 horas',final:'7 días',tacto:'1,5 horas'},
      preparacion:'Superficie limpia, seca, desengrasada, libre de polvo, óxido, partes flojas y hongos.',
      aplicacion:'Pincel, rodillo o soplete, con consistencia normal o mínima cantidad de agua.',
      acabado:'Mate gris',
      uso:'Base interior y exterior para realzar colores de bajo poder cubritivo.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',
      estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'funguicida-insecticida-maderas',
      nombre:'Funguicida - Insecticida para Maderas',
      categoria:'Maderas y protección',
      unidad:'litros',
      rendimiento:{min:3,max:4,type:'areaPerUnitPerCoat',display:'3 a 4 m² por litro y por mano'},
      envases:[1,5],
      manosDefault:3,manosOpciones:[3],
      manosRecomendadas:'A pincel, aplicar como mínimo 3 manos abundantes.',
      recomendaciones:'Producto moderadamente tóxico. Aplicar sin diluir sobre madera nueva y trabajar con protección adecuada.',
      tiempos:{entreManos:'No especificado en la ficha',final:'24 horas',tacto:'5 horas'},
      preparacion:'Madera nueva, limpia, lijada, seca y libre de polvo, grasas, aceites, jabones, ceras y tratamientos anteriores.',
      aplicacion:'Pincel, soplete a baja presión o inmersión durante 5 a 15 minutos.',
      acabado:'Amarillo pálido translúcido; no altera el aspecto de la madera',
      uso:'Protección preventiva contra insectos xilófagos y hongos.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',
      estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'limpia-metal-concentrado',
      nombre:'Limpia Metal Concentrado',
      categoria:'Limpieza y preparación',
      calculable:false,
      unidad:'litros',
      rendimiento:{type:'informational',display:'La ficha no informa rendimiento por m². Dilución normal: 1 parte de producto en 10 partes de agua'},
      envases:[1,5],
      manosDefault:1,manosOpciones:[1],
      manosRecomendadas:'Aplicar por sectores y verificar la efectividad de la limpieza.',
      recomendaciones:'Producto ácido y corrosivo. Usar guantes, protección ocular y ventilación. Pintar el metal antes de 24 horas.',
      tiempos:{entreManos:'No corresponde',final:'Actuación aproximada: 10 minutos',tacto:'No corresponde'},
      preparacion:'Retirar óxido de laminación excesivo con cepillo de alambre o tela esmeril.',
      aplicacion:'Pincel, cepillo, trapo o inmersión; retirar sin dejar restos acuosos y secar completamente.',
      acabado:'Transparente',
      uso:'Desengrasante, desoxidante y fosfatizante para metales nuevos u oxidados.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',
      estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'masilla-interior-construccion-seco',
      nombre:'Masilla Interior para Construcción en Seco',
      categoria:'Masillas y preparación',
      unidad:'litros',
      rendimiento:{min:1,max:1,type:'areaPerUnitPerCoat',display:'1 m² por litro con espesor uniforme de 1 mm'},
      envases:[1,4,10,20],
      manosDefault:1,manosOpciones:[1,2,3],
      manosRecomendadas:'La cantidad de capas depende de las exigencias del trabajo.',
      recomendaciones:'Aplicar siempre en capas delgadas. Puede agregarse una pequeña cantidad de agua si fuera necesario.',
      tiempos:{entreManos:'No especificado en la ficha',final:'8 horas',tacto:'No especificado en la ficha'},
      preparacion:'Superficie firme, limpia y libre de polvo y partes flojas.',
      aplicacion:'Espátula, goma o llana metálica.',
      acabado:'Liso y lijable',
      uso:'Corrección y terminación de superficies interiores de construcción en seco.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',
      estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'masilla-madera-color-pino',
      nombre:'Masilla para Madera Color Pino',
      categoria:'Masillas y preparación',
      calculable:false,
      unidad:'gramos',
      rendimiento:{type:'informational',display:'La ficha no informa rendimiento por superficie'},
      envases:[400],
      packageLabels:{'400':'Envase de 400 g'},
      manosDefault:1,manosOpciones:[1,2,3],
      manosRecomendadas:'Aplicar las capas necesarias según la profundidad de la reparación.',
      recomendaciones:'En exterior debe protegerse posteriormente con un recubrimiento impermeable para madera.',
      tiempos:{entreManos:'2 horas',final:'12 horas',tacto:'Lijado a partir de 3 horas'},
      preparacion:'Homogeneizar y comprobar previamente el color en una zona no visible.',
      aplicacion:'Espátula; lijar una vez seca.',
      acabado:'Color pino',
      uso:'Relleno de rayaduras, golpes e imperfecciones en madera o placas.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',
      estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'mateante-esmaltes-barnices',
      nombre:'Mateante para Esmaltes Sintéticos y Barnices',
      categoria:'Aditivos',
      calculable:false,
      unidad:'envase',
      rendimiento:{type:'informational',display:'Satinado: 250 cm³ cada 2 L. Mate: 250 cm³ cada 1 L'},
      envases:[0.25],
      packageLabels:{'0.25':'Envase de 250 cm³'},
      manosDefault:1,manosOpciones:[1],
      manosRecomendadas:'Incorporar al esmalte o barniz brillante antes de aplicar.',
      recomendaciones:'Compatible con pinturas alquídicas base aguarrás.',
      tiempos:{entreManos:'Depende del producto modificado',final:'Depende del producto modificado',tacto:'No corresponde'},
      preparacion:'Mezclar hasta lograr una distribución uniforme.',
      aplicacion:'Aditivo para mezcla.',
      acabado:'Satinado o mate según dosificación',
      uso:'Disminución del brillo de esmaltes sintéticos y barnices brillantes.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',
      estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'membrana-pasta-poliuretanica',
      nombre:'Membrana en Pasta Poliuretánica',
      categoria:'Techos e impermeabilización',
      unidad:'kg',
      rendimiento:{min:1,max:1.25,type:'quantityPerAreaFinished',display:'1 a 1,25 kg/m² de trabajo terminado con 4 manos'},
      envases:[1.25,5,10,20],
      manosDefault:4,manosOpciones:[4],
      manosRecomendadas:'4 manos para lograr un espesor superior a 500 micrómetros.',
      recomendaciones:'El consumo corresponde al trabajo terminado; no debe multiplicarse nuevamente por la cantidad de manos.',
      tiempos:{entreManos:'4 horas',final:'24 horas',tacto:'Coalescencia UV: 7 días de sol'},
      preparacion:'Superficie limpia, seca, desengrasada, libre de polvo, óxido y partes flojas.',
      aplicacion:'Pincel o rodillo.',
      acabado:'Impermeable y atérmico',
      uso:'Impermeabilización de techos con pendiente superior al 1%, losas, revoques y ladrillos.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',
      estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'removedor-gel',
      nombre:'Removedor Gel',
      categoria:'Limpieza y preparación',
      calculable:false,
      unidad:'litros',
      rendimiento:{type:'informational',display:'La ficha impresa indica 3 a 5 m³ por litro y por mano; unidad inconsistente, por lo que se bloquea el cálculo'},
      envases:[0.5,1],
      manosDefault:1,manosOpciones:[1],
      manosRecomendadas:'Realizar una aplicación por cada capa de pintura que deba retirarse.',
      recomendaciones:'Usar guantes, máscara y ventilación. Aplicar una capa aproximada de 2 mm y dejar actuar 10 minutos.',
      tiempos:{entreManos:'Según cantidad de capas a remover',final:'Actuación aproximada: 10 minutos',tacto:'No corresponde'},
      preparacion:'Agitar antes de cada aplicación.',
      aplicacion:'Pincel sin estirar; retirar el material ablandado con espátula o estropajo.',
      acabado:'Gel removedor',
      uso:'Remoción de pinturas y barnices.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',
      estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'sellador-acrilico-pintable-multiuso',
      nombre:'Sellador Acrílico Pintable Multiuso',
      categoria:'Selladores y juntas',
      calculable:false,
      unidad:'litros',
      rendimiento:{type:'informational',display:'Junta de 0,5 × 0,5 cm: aproximadamente 50 cm³ por metro lineal'},
      envases:[0.25,0.3,1],
      packageLabels:{'0.25':'Pomo de 250 cm³','0.3':'Cartucho de 300 cm³','1':'Envase de 1 L'},
      manosDefault:1,manosOpciones:[1],
      manosRecomendadas:'Rellenar y alisar la junta en una sola operación.',
      recomendaciones:'No utilizar en zonas sumergidas ni con contacto permanente con agentes químicos agresivos. No puede lijarse.',
      tiempos:{entreManos:'No corresponde',final:'24 horas aproximadamente',tacto:'Secado superficial: 12 a 24 horas'},
      preparacion:'Junta limpia, firme, seca y libre de polvo y elementos extraños.',
      aplicacion:'Pomo, cartucho o espátula; alisar después de colocar.',
      acabado:'Mate blanco y pintable con látex',
      uso:'Juntas, encuentros, fisuras y rajaduras con movimientos moderados.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',
      estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    },
    {
      id:'siliconado-ladrillos-base-solvente',
      nombre:'Siliconado para Ladrillos - Base Solvente',
      categoria:'Impermeabilización',
      unidad:'litros',
      rendimiento:{min:5,max:10,type:'areaPerUnitPerCoat',display:'5 a 10 m² por litro y por mano'},
      envases:[1,4,20],
      manosDefault:3,manosOpciones:[3],
      manosRecomendadas:'La ficha indica 3 manos sin diluir.',
      recomendaciones:'No requiere fondo. Si existe una película anterior, debe eliminarse totalmente para permitir la penetración.',
      tiempos:{entreManos:'No especificado en la ficha',final:'24 horas',tacto:'No especificado en la ficha'},
      preparacion:'Ladrillo limpio, seco, desengrasado, libre de polvo y hongos.',
      aplicacion:'Pincel o soplete, sin diluir.',
      acabado:'Mate incoloro, sin película visible',
      uso:'Hidrorrepelencia de ladrillos interiores y exteriores sin modificar su aspecto natural.',
      revision:1,versionFicha:'1.0',fechaActualizacion:'2026-07-24',
      estadoFicha:'vigente',fuenteFicha:'Ficha técnica FADEPA',searchVersion:1
    }
  ];

  const current=Array.isArray(window.PRODUCTS)?window.PRODUCTS:[];
  const ids=new Set(current.map(p=>p.id));
  window.PRODUCTS=current.concat(products.filter(p=>!ids.has(p.id)));
})();
